# Problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first terms will be:
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

f1 = 1
f2 = 2

sum_ev_fib_num = 0

while f1 <= 4000000:
    if f1 % 2 == 0:
        sum_ev_fib_num += f1
    f1, f2 = f2, f1 + f2

print(sum_ev_fib_num)